# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
    - run: yarn
    - run: yarn run build
    
    - name: Vue to Github Pages
        # You may pin to the exact commit or the version.
        # uses: xRealNeon/VuePagesAction@1fe4d0b38025bcbaafa71a359dd5c02f33bb03b7
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        # Your username
        username: CI
        reponame: web-ui
        # Your Github token
        token: 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
        # Your git commit email
        gitemail: ci@thinkmoon.cn
        # Your git commit name
        gitname: CI
        # Your git commit message
        gitmsg: deploy
        # Your custom domain
